[env:t5_epaper_s3_pro]
platform = espressif32 @ 6.5.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.psram_type = opi

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3
    -DAURA_VERSION=\"0.1.0-bringup\"
    -mfix-esp32-psram-cache-issue

lib_deps =
    adafruit/Adafruit BMP5xx Library @ ^1.0
    adafruit/Adafruit LSM6DS @ ^4.7
    adafruit/Adafruit BNO08x @ ^1.2
    adafruit/Adafruit SHT4x Library @ ^1.0
    adafruit/Adafruit BusIO @ ^1.16
    lewisxhe/XPowersLib @ ^0.2.3
    bblanchon/ArduinoJson @ ^7.0
