#!/usr/bin/env python3
"""
gen_boot_asset.py  —  AURA "Krücke" boot-logo asset generator (KIE Engineering)

Turns the grey logo lockup into a panel-ready 16-grey (4-bit) Floyd-Steinberg
bitmap and emits a C header (boot_logo.h) plus a PNG preview.

WHY PILLOW-ONLY:
  The SVG->PNG step (cairosvg) needs system cairo libs and is painful on Windows.
  So that step is done ONCE (off-machine) and the result committed as the source
  raster `boot_logo_src_grey.png`. This script only needs Pillow, which installs
  cleanly on Windows:  pip install pillow

INPUT  (committed in repo):
  boot_logo_src_grey.png   8-bit grey logo on WHITE, hi-res (>=4x target)
OUTPUT:
  boot_logo.h                  4-bit grey array, 0=black .. 15=white, 1 byte/px
  boot_logo_<W>x<H>_dither.png preview of exactly what the panel will show

REGENERATE THE SOURCE RASTER (only if the logo SVG changes; needs cairosvg):
  cairosvg aura-logo-grayscale.svg -o boot_logo_src_grey.png \
           --output-width 1112 --output-height 1360 -b "#FFFFFF"

USAGE:
  python gen_boot_asset.py                 # uses defaults below
  python gen_boot_asset.py --height 340    # change on-glass height (W follows aspect)
"""
import argparse, os
from PIL import Image

SRC      = "boot_logo_src_grey.png"
LOGO_AR  = 360 / 440            # source SVG aspect (w/h)
GREY_LV  = 16                   # panel grey levels (4-bit)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=SRC)
    ap.add_argument("--height", type=int, default=340, help="on-glass logo height in px")
    ap.add_argument("--out-header", default="boot_logo.h")
    ap.add_argument("--out-preview", default=None)
    args = ap.parse_args()

    H = args.height
    W = round(H * LOGO_AR)
    preview = args.out_preview or f"boot_logo_{W}x{H}_dither.png"

    if not os.path.exists(args.src):
        raise SystemExit(f"missing source raster: {args.src}\n"
                         f"regenerate it from aura-logo-grayscale.svg (see header of this file)")

    src = Image.open(args.src).convert("L")
    small = src.resize((W, H), Image.LANCZOS)

    # 16-level grey palette + Floyd-Steinberg dither (matches on-panel rendering)
    levels = [round(i * 255 / (GREY_LV - 1)) for i in range(GREY_LV)]
    pal = []
    for v in levels:
        pal += [v, v, v]
    pal += [0, 0, 0] * (256 - GREY_LV)
    pim = Image.new("P", (16, 16))
    pim.putpalette(pal)
    dith = small.convert("RGB").quantize(palette=pim, dither=Image.Dither.FLOYDSTEINBERG).convert("L")
    dith.save(preview)

    # emit 4-bit levels (0..15), 0=black 15=white, row-major, 1 byte/px
    data = list(dith.getdata())
    lv = [round(p / 255 * (GREY_LV - 1)) for p in data]

    out = []
    out.append("// boot_logo.h — AUTO-GENERATED by tools/gen_boot_asset.py — do not hand-edit")
    out.append('// AURA "Kruecke" boot lockup, 16-grey (4-bit) Floyd-Steinberg dithered.')
    out.append("// Level convention: 0 = black (ink), 15 = white (paper). 1 byte per pixel.")
    out.append("#pragma once")
    out.append("#include <stdint.h>")
    out.append(f"#define BOOT_LOGO_W {W}")
    out.append(f"#define BOOT_LOGO_H {H}")
    out.append(f"static const uint8_t boot_logo[{W*H}] = {{")
    for r in range(H):
        row = lv[r * W:(r + 1) * W]
        out.append("  " + ",".join(map(str, row)) + ",")
    out.append("};")
    with open(args.out_header, "w") as f:
        f.write("\n".join(out) + "\n")

    print(f"wrote {args.out_header}  ({W}x{H} = {W*H} px)")
    print(f"wrote {preview}")

if __name__ == "__main__":
    main()
