#pragma once
// boot_splash.h — AURA boot logo blit for epdiy 2.0.0
//
// Panel: ED047TC1 960x540 LANDSCAPE (native, no rotation)
// Logo: generated by gen_boot_asset.py, centered on display
//
// NOTE: epd_draw_pixel writes to native framebuffer coordinates.
// epd_set_rotation does NOT transform pixel coordinates.

#include "epdiy.h"
#include "epd_highlevel.h"
#include "boot_logo.h"

// Centered on 960x540 landscape
static constexpr int LOGO_X = (960 - BOOT_LOGO_W) / 2;
static constexpr int LOGO_Y = (540 - BOOT_LOGO_H) / 2;

// Mild S-curve: darks slightly darker (tree/branches), lights stay soft.
// Linear would be: 0,17,34,51,68,85,102,119,136,153,170,187,204,221,238,255
// This curve: darks 0-7 pushed ~15% darker, lights 8-15 nearly unchanged.
static const uint8_t GAMMA_LUT[16] = {
    0, 10, 22, 38, 55, 72, 90, 110, 132, 153, 174, 194, 213, 230, 244, 255
};

/// Blit the boot logo into the epdiy framebuffer (native landscape coords).
static void blitBootLogo(uint8_t *fb) {
    for (int y = 0; y < BOOT_LOGO_H; y++) {
        for (int x = 0; x < BOOT_LOGO_W; x++) {
            uint8_t lvl = boot_logo[y * BOOT_LOGO_W + x];
            uint8_t grey = GAMMA_LUT[lvl];
            epd_draw_pixel(LOGO_X + x, LOGO_Y + y, grey, fb);
        }
    }
}

/// Full boot splash: logo auf weissem Hintergrund via GC16.
/// KEIN epd_clear() — das bringt das HL-State-Tracking durcheinander.
static void showBootSplash(EpdiyHighlevelState *hl, const char *version) {
    uint8_t *fb = epd_hl_get_framebuffer(hl);
    epd_hl_set_all_white(hl);
    blitBootLogo(fb);

    epd_poweron();
    epd_hl_update_screen(hl, MODE_GC16, (int)epd_ambient_temperature());
    epd_poweroff();
}
